// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.7;
pragma abicoder v2;

// ============================================================================
// ShadowBase — Poseidon Hash Library Stubs
// Forked from: Railgun-Privacy/contract/contracts/logic/Poseidon.sol
//
// These are stubs for the Solidity compiler to generate the correct interface.
// The actual deployed bytecode is generated by the circomlib toolchain.
// For predeploy deployment, the real Poseidon bytecode must be deployed
// at the library addresses in genesis.
// ============================================================================

library PoseidonT3 {
    // solhint-disable-next-line no-empty-blocks
    function poseidon(bytes32[2] memory input) public pure returns (bytes32) {}
}

library PoseidonT4 {
    // solhint-disable-next-line no-empty-blocks
    function poseidon(bytes32[3] memory input) public pure returns (bytes32) {}
}
